### PR TITLE
change the $.get out of Jquery

### PR DESCRIPTION
**Pull request by zmofei**
see exports.loadScript

### CODE REVIEW

**Comment by bh-lay** [comment]
yeah! now I use script and link tag to load js and css resources !

**Comment by TechQuery** [comment]
@zmofei **XHR** 没法加载 **跨域资源** 啊……

**Comment by bh-lay** [comment]
issue不是你想开，想开就能开，现在又要close，把我哄回来！

**Comment by zmofei** [comment]
小哥哥小哥哥，这是PR不是issue哦

**Pull request closed without merging**
